### ISSUE TITLE
Upgrade Entity-Relationships tutorial to organic farming ?

### ISSUE THREAD

**Issue by fbattello** [FIWARE/tutorials.Entity-Relationships#25]
Hello,

It's not a software issue, rather an ecological concern.
Could it be a good idea to get rid of Herbicide entities and the related task named "Spray Herbicide XXX on field Y" ?
It's much easier to operate this ecological transition by software :)

**Comment by jason-fox** [comment]
One suggestion would be to swap the product to an organic [fish hydrolysate](https://www.gardenmyths.com/fish-fertilizer-worth-buying/) as a natural fertilizer. What do you think?

**Comment by fbattello** [comment]
I fully agree. I understand that the current example technically serves very well its purpose.
But a natural fertilizer would be a great example, inline with the new CAP 2023-27 that promotes biodiversity and the transition to sustainable food systems, 
Ideally I would like to spray no product at all in my organic farm :)
But why not trying fish hydrolysate ?

**Comment by kzangeli** [comment]
Love it ! :)
