### ISSUE TITLE
A typo in documentation and issue with q parameter

### ISSUE THREAD

**Issue by johnnychoque** [FIWARE/tutorials.Entity-Relationships#29]
Hi all, 

Apparently, I found a typo in the tutorials.Entity-Relationships documentation for NGSI-LD Stellio. I think the controlledAsset attribute does not exist and should be controllingAsset instead.

Despite correcting that attribute, request 7 does not return a response although it returns status 200.

On the other hand, requests 10 and 11 also do not return a response even though they have status 200.

Can you give me an idea of how to fix these issues?

Request 7: https://github.com/FIWARE/tutorials.Entity-Relationships/tree/NGSI-LD#seven-request
Request 10: https://github.com/FIWARE/tutorials.Entity-Relationships/tree/NGSI-LD#onezero-request
Request 11: https://github.com/FIWARE/tutorials.Entity-Relationships/tree/NGSI-LD#oneone-request

Regards,

Johnny

**Comment by jason-fox** [comment]
There was an typo in the 4th Request - it should have read `controlledAsset` not `controllingAsset` - this caused the subsequent requests to refer to a non-existent relationship. I've fixed the `README` and the docs.

```diff
 curl -L 'http://localhost:1026/ngsi-ld/v1/entityOperations/update?options=update' \
 -H 'Content-Type: application/json' \
 -H 'Link: <http://context/ngsi-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
 -d '[
     {
         "id": "urn:ngsi-ld:TemperatureSensor:001",
         "type": "TemperatureSensor",
-        "controllingAsset": {
+        "controlledAsset": {
             "type": "Relationship",
             "object": "urn:ngsi-ld:Building:farm001"
         }
     },
     {
         "id": "urn:ngsi-ld:TemperatureSensor:002",
         "type": "TemperatureSensor",
-        "controllingAsset": {
+        "controlledAsset": {
             "type": "Relationship",
             "object": "urn:ngsi-ld:Building:barn002"
         }
     },
...etc.
```

Funnily enough the Japanese version of the `README` was correct, so the real fix was to learn to read Japanese.
